FROM python:2

RUN apt-get update && apt-get install -y \
		libopenblas-base \
		mklibs \		
	--no-install-recommends && rm -r /var/lib/apt/lists/*

RUN pip install --no-cache-dir numpy
RUN pip install --no-cache-dir pylab
